USE filmes;
CREATE TABLE Pais (
	IDPais INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(50) NOT NULL
);

CREATE TABLE Ator (
    IDAtor INTEGER PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL,
    IDPais INTEGER NOT NULL,
    DataNascimento DATE NOT NULL,
    FOREIGN KEY (IDPais) REFERENCES pais(IDPais)
);

CREATE TABLE Premio (
	IDPremio INT PRIMARY KEY,
    NomePremio VARCHAR(50) NOT NULL
);

CREATE TABLE EdicaoPremio (
	IDEdicaoPremio INT PRIMARY KEY AUTO_INCREMENT,
    IDPremio INT NOT NULL,
    AnoEdicao YEAR NOT NULL,
	NomeEdicao VARCHAR(50),
    FOREIGN KEY (IDPremio) REFERENCES Premio(IDPremio) 
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CategoriaPremio (
	IDCategoriaPremio INT PRIMARY KEY AUTO_INCREMENT,
    IDEdicaoPremio INT NOT NULL,
    NomeCategoria VARCHAR(50),
    IDAtor INT,
    FOREIGN KEY (IDAtor) REFERENCES Ator (IDAtor),
    FOREIGN KEY (IDEdicaoPremio) REFERENCES 
    EdicaoPremio(IDEdicaoPremio) ON DELETE CASCADE ON UPDATE CASCADE
);

